
=== Runtime Dependencies

As you saw before (`<<_app_info_yaml,app-info.yaml>>`), *Applications* can declare dependencies to third-party *Manifests*. These *Manifests* are hosted in *Software Repositories* on the *BDeploy* Server.

To make them available on the server, you need to:

* Use `bhive import` to import the directory containing the third-party software into a local *BHive*.
* Use `bhive push` to push the created *Manifest* to the *Software Repository* of your choice.

==== Manifest Naming

Third party software *Manifests* can have basically any name. If you want to provide different *Manifests* per target operating system though, you will have to follow a simple naming rule: append the operating system name to the *Manifest* name part, e.g.:

* `my/external/software/windows:1.0.0`
* `my/external/software/linux:1.0.0`

It can then be referenced by an `app-info.yaml` using the short-hand syntax `my/external/software:1.0.0` and *BDeploy* will choose the correct one depending on the target operating system.
