# yaml-language-server: $schema=https://localhost:7701/api/public/v1/schema/productInfoYaml

name: "Demo Product"
product: "io.bdeploy/demo"
vendor: BDeploy Team
configTemplates: config
versionFile: "product-version.yaml"

applications:
  - "server-app"
  - "client-app"

instanceTemplates:
  - "instance-template-default.yaml"
  - "instance-template-override.yaml"

instanceVariableDefinitions:
  - "instance-variable-definition.yaml"

applicationTemplates:
  - "app-templates/server-with-sleep.yaml"
  - "app-templates/server-with-template.yaml"

parameterTemplates:
  - "param-templates/shared.yaml"

instanceVariableTemplates:
  - "instance-variable-template.yaml"
