name: "Demo Chat App"
product: "io.bdeploy/chat-app"
vendor: BDeploy Team
applications:
  - "chat-app"

applicationTemplates:
  - "app-templates/app-template-invalid-1.yaml"
  - "app-templates/app-template-invalid-2.yaml"
  - "app-templates/app-template-invalid-3.yaml"
  - "app-templates/app-template-https.yaml"

instanceTemplates:
  - "instance-template-default.yaml"
  - "instance-template-invalid.yaml"
  - "instance-template-overrides.yaml"

versionFile: "product-version.yaml"
