== UI Front- and Backend

Contains the angular configuration frontend as well as the matching backend.

=== Theming

The `app-theme.scss` currently supports a dark and a light theme. Components can contribute their own themes using SCSS mixins. This has the advantage that the component theme can access theme colors without knowing their exact definition. Whether the theme is dark or light (generally speaking) can be queried, so defining new (own) colors can be made dependent on that.

To create a theme mixin for any component:

- Create a new .scss file in the component's folder, e.g. `my-component.scss`.
- Import angular material theming support
- Define a mixin with your theme selectors (attention, those are application global, so be careful with naming them).
- Import and include the new mixin in the global `app-theme.scss`

A very simple custom component's scss file could look like this:

----
@import '~@angular/material/theming';

@mixin my-component-theme($theme) {
  .my-component-class {
  	background-color: mat-color(map-get($theme, warn));
  }
}
----

This will create a CSS class using the current themes 'warn' color as background.

Now you need to include and import the theme in the global `app-theme.scss` file:

----
@import '~@angular/material/theming';
@include mat-core();

/* Custom component theme collection */
@import 'app/my-component/my-component-theme.scss';
@import ... (other component themes)

@mixin all-themes($theme) {
  // general angular material theme
  @include angular-material-theme($theme);

  // application themes
  @include my-component-theme($theme);
  @include ... (other component themes)
}

... (rest of file)
----

==== Accessing theme properties in a mixin

Angular material defines a few properties. Those can be accessed from within a mixin easily. Basically a SCSS selector/mixin is just a map, so `map-get` can be used to access the actual values.

----
@import '~@angular/material/theming';

@mixin my-component-theme($theme) {
  $dark: map-get($theme, is-dark);

  $color-light: rgb(230, 255, 230);
  $color-dark: rgb(42, 56, 42);

  .my-component-class {
    background-color: if($dark, $color-dark, $color-light);
  }
}
----

As you can see the `is-dark` property of the theme is queried here. If the value is true, `$color-dark` is used, otherwise `$color-light` is used.

Available attributes are:

- `primary` - the primary palette, can be used with `mat-color`
- `accent` - the secondary palette, can be used with `mat-color`
- `warn` - the warn palette, can be used with `mat-color`
- `is-dark` - boolean determining whether the theme is dark or light.
- `foreground` - complex map containing various foreground colors.
- `background` - complex map containing various background colors.

==== Palettes

Every theme has a `primary`, `accent` and `warn` palette. You can access those colors using `mat-color`.

----
@mixin my-component-theme($theme) {
  $accent-palette: map-get($theme, accent);
  
  $bg-color-lighter: mat-color($accent-palette, lighter);
  $bg-color-normal: mat-color($accent-palette);
  $bg-color-darker: mat-color($accent-palette, darker);
  
  .my-component-class {
  	background-color: $bg-color-lighter;
  }
}
----

`mat-color` accepts a palette as argument. This can be either of the theme palettes. An optional second argument can be either `lighter`, `darker` or a dedicated index into the palette to choose a certain color intensity explicitly.

==== Foreground Colors

The complex foreground map has the following named color definitions:

- `base`
- `divider`
- `dividers`
- `disabled`
- `disabled-button`
- `disabled-text`
- `elevation`
- `hint-text`
- `secondary-text`
- `icon`
- `icons`
- `text`
- `slider-min`
- `slider-off`
- `slider-off-active`

Each of those can be accessed by `map-get`-ting them:

----
@mixin my-component-theme($theme) {
  $background-colors: map-get($theme, background);
  
  .my-component-class {
  	background-color: map-get($background-colors, app-bar);
  }
}
----

This example will use the `app-bar` map key in the complex `background` map entry of the current theme.

==== Background Colors

Analogous to foreground colors, these background colors are defined.

- `status-bar`
- `app-bar`
- `background`
- `hover`
- `card`
- `dialog`
- `disabled-button`
- `raised-button`
- `focused-button`
- `selected-button`
- `selected-disabled-button`
- `disabled-button-toggle`
- `unselected-chip`
- `disabled-list-option`

Using these foreground colors works exactly the same as background colors do.