:prewrap!:
= Getting Started (CLI)

This guide will walk through the different steps required to bring a single product from a development workspace to a target server.

FIXME: This needs a major rework.

== Prerequisites

=== Application Setup

Build the latest versions of the command line applications in the workspace using `./gradlew build` as usual. The distributions will reside in the `minion/build/distributions`, `bhive/build/distributions` and `minion-client/build/distributions` directories respectively. Grab the ZIP files (for your platform) and unpack them. Setup PATH so that `minion`, `minion-client` and `bhive` from the `bin` directories are executable from the command line.

=== Product Applications

The applications for the product you are going to deploy need to be available, including the `app-info.yaml` descriptor for them. An application is any directory tree including any form of binaries, along with said descriptor. A template for the descriptor can be generated using `minion template --app`.

This walkthrough will assume a WAMAS product with three applications: `settings-server`, `message-server` and `workerprocess-server`. The according `app-info.yaml` files used at the time of writing can be found https://git.ssi-schaefer.com/c/products/wamas/+/7442[here].

Create the applications by exporting the according three products from a WAMAS (minimum 5.8.1) workspace. Unzip the resulting ZIP file(s) for your platform from the `workspace/02_BUILD_PRODUCT` directory (by default) into a temporary directory. If there are no `app-info.yaml` files in the ZIP files already, put the ones referenced above into the unpacked applications.

== Walkthrough

=== Master Init

The first step is to create a new master. A master will always also include a single slave (itself), so creating a master is sufficient to be able to use the target server for deployment. Run this:

----
$ minion init --root=/path/to/root --dist=/path/to/minion/build/distributions/minion-linux64-1.0.0.XXX.zip  --hostname=fril0041.wamas.com --tokenFile=token.txt
----

The path given for `--root` is the path where the master's data will reside. The path given for `--dist` is the path to the ZIP file that the `minion` binary was extracted from. If you don't have this at hand, pass `ignore` as value to this argument - the master will always report that it is outdated in this case, causing a remote update if a remote client checks for this. The `--hostname` argument is solely used later on to expand application parameters which need to know the name of the host they are running on. BDeploy itself does not interpret or use this value at all. For local-only deployments you can use `localhost`. Finally, the `--tokenFile` argument names a file to put the master access token pack into. You will need this whenever you want to remotely access the master. 

=== Start the Master

The master can now be started like this:

----
$ minion master --root=/path/to/root
----

NOTE: the process will keep running, so you will need another shell to continue with the rest of the walkthrough.

=== Import Applications

We will use a temporary (local) hive to import applications and prepare the product and instance configuration. This hive is just a (non-existing) path on the filesystem, so choose any. You will need to have the application directories at hand as described in <<Product Applications>>.

----
$ bhive import --hive=/local/hive --source=/apps/settings-server --manifest=wamas/settings-server:5.8.1-first
$ bhive import --hive=/local/hive --source=/apps/jms-server --manifest=wamas/message-server:5.8.1-first
$ bhive import --hive=/local/hive --source=/apps/workerprocess-server --manifest=wamas/workerprocess-server:5.8.1-first
----

The `--source` is the directory containing the application along with it's app-info.yaml file. The `--manifest` is the name which the applicaiton will be imported as. After the import operation, the three applications will be available in the `/local/hive` hive. Running the following command will yield similar output:

----
$ bhive manifest --hive=/local/hive --list
wamas/message-server:5.8.1-first                                       0cba5888f7bd1438a7fd8947721700b2d93a315a
wamas/settings-server:5.8.1-first                                      d163c93d48e852b8fd8b4fc96413c3dc2ac32c65
wamas/workerprocess-server:5.8.1-first                                 e2e0fdd3195b29ca403e6803a739c95604d252e6
----

=== Create Product

Once all applications for a product "bundle" are available in a hive, you can create a "product" which is simply a bhive manifest which references all applications which belong to this product:

----
$ minion product --hive=/local/hive --add=wamas/product:5.8.1-first --name="WAMAS 5.8.1" --applications=wamas/message-server:5.8.1-first,wamas/workerprocess-server:5.8.1-first,wamas/settings-server:5.8.1-first
----

Now running the following will yield output like this:

----
$ minion product --hive=/local/hive --list -v
wamas/product:5.8.1-first      WAMAS 5.8.1
  wamas/message-server:5.8.1-first WAMAS Message Server
  wamas/settings-server:5.8.1-first WAMAS Settings Server
  wamas/workerprocess-server:5.8.1-first WAMAS Worker Process
----

=== Import Requirements for the Applications

The mentioned `app-info.yaml` files mention a requirement for a certain manifest: `openjdk/jre8`. We need to make sure that it is present before the product can be deployed:

----
$ bhive import --hive=/local/hive --source=/path/to/jdk8/jre --manifest=openjdk/jre8:1.8.0_121
----

=== Create Instance Configuration

This is a task usually performed by the user interface running on the master/central master. To show the way around for the pure command line deployment, we'll use a development tool here:

----
$ minion template --product=wamas/product:5.8.1-first --hive=/local/hive --template=/local/template --create
----

The `--template` directory will be created and populated with a few files:

----
$ find template/
template/
template/config
template/config/logging
template/config/logging/log4j-ServerApplication-Settings_Server.xml
template/config/logging/log4j-standard.xml
template/config/logging/log4j-legacy.properties
template/template.json
----

Edit the `template.json` file with your favorite editor. The only *required* change in there should be the database connection. Copy the encrypted DB connection string for a database of your choice from a WAMAS IDE (edit DB connection and press "Copy raw connection string to clipboard..."). Make sure the database is running (i.e. H2) before launching the application later on.

IMPORTANT: The template will be generated with a random generated UUID already - you can change it, but make sure to replace all occurences of the UUID in the `template.json`

=== Import template/Create instance

Now that the template is according to your wishes, you can create a new instance configuration in the local hive using:

----
$ minion template --load --hive=/local/hive --template=/local/template
----

This will create two new manifests, both using the UUID mentioned in `template.json` - in my test case this was `q78u-1z-0h5p`. Running a manifest list command on the local hive once more should yield this:

----
$ bhive manifest --hive=/local/hive --list
openjdk/jre8:1.8.0_121                                                 8e9ed64358707944b11079ab55e3c8a1524c67ad
q78u-1z-0h5p/master:1                                                  8d67307247c77935a628db63e17b8532b5de286d
q78u-1z-0h5p/root:1                                                    481f16a20d4385aa3ebb55bb8d8a8a36d448647a
wamas/message-server:5.8.1-first                                       0cba5888f7bd1438a7fd8947721700b2d93a315a
wamas/product:5.8.1-first                                              dfe5b33df37f6f3ed12acf7e0bd94ae8e6e8ea33
wamas/settings-server:5.8.1-first                                      d163c93d48e852b8fd8b4fc96413c3dc2ac32c65
wamas/workerprocess-server:5.8.1-first                                 e2e0fdd3195b29ca403e6803a739c95604d252e6
----

=== Create demo customer

Before pushing the instance to the remote, we want a customer-specific hive to exist on the remote. We need to create it. To create a hive on the remote, the remote storage location for the hive needs to be specified (a master can have more than one storage location). List existing storage locations using (on the server machine):

----
$ minion storage --list --root=/path/to/root
/path/to/root/storage
----

The default storage directory is a `storage` subdirectory of the used root.

Now run on the client:

----
$ minion-client customer --remote=https://localhost:7701/api --tokenFile=token.txt --create=demo --description="Demo Customer" --storage="/path/to/root/storage"
----

NOTE: You need the `token.txt` created during <<Master Init>>.

=== Push to remote

Now that the "demo" customer exists, we can push required pieces to it's dedicated remote hive:

----
$ bhive push --hive=/local/hive --remote=https://localhost:7701/api --tokenFile=token.txt --manifest=wamas/product:5.8.1-first --name=demo
$ bhive push --hive=/local/hive --remote=https://localhost:7701/api --name=demo --tokenFile=token.txt --manifest=openjdk/jre8:1.8.0_121
----

You need to push both the product as well as the JRE manifest. This allows individual updates of loosely coupled manifests.

You can verify that all required pieces landed on the remote using this command:

----
$ bhive manifest --list --remote=https://localhost:7701/api --tokenFile=token.txt --name=demo
meta/customer:1                                                        14400ab7b80337c4c09b6fd88fb41ba09ba6f42a
openjdk/jre8:1.8.0_121                                                 8e9ed64358707944b11079ab55e3c8a1524c67ad
q78u-1z-0h5p/master:1                                                  8d67307247c77935a628db63e17b8532b5de286d
q78u-1z-0h5p/root:1                                                    481f16a20d4385aa3ebb55bb8d8a8a36d448647a
wamas/message-server:5.8.1-first                                       0cba5888f7bd1438a7fd8947721700b2d93a315a
wamas/product:5.8.1-first                                              dfe5b33df37f6f3ed12acf7e0bd94ae8e6e8ea33
wamas/settings-server:5.8.1-first                                      d163c93d48e852b8fd8b4fc96413c3dc2ac32c65
wamas/workerprocess-server:5.8.1-first                                 e2e0fdd3195b29ca403e6803a739c95604d252e6
----

=== Trigger deployment

Execute (on the client):

----
$ minion-client deployment --remote=https://localhost:7701/api --tokenFile=token.txt --deploy --name=demo --manifest=q78u-1z-0h5p/root:1
----

IMPORTANT: Make sure to replace the manifest name with the one matching your generated UUID.

=== Activate deployment

Activating a deployment marks a deployed instance version's applications as those which are started when an application start request is received.

----
$ minion-client deployment --remote=https://localhost:7701/api --tokenFile=token.txt --name=demo --activate --manifest=q78u-1z-0h5p/root:1
----

Verify that the deployment is active using this command:

----
$ minion-client deployment --remote=https://localhost:7701/api --tokenFile=token.txt --name=demo --list
UUID            MANIFEST                       ACTIVE    
q78u-1z-0h5p    q78u-1z-0h5p/root:1            *         
----

=== Process control

For this initial demo setup, there is not auto-start configured, so each application needs to be started individually. Usually this would happen from a UI as well...

----
$ minion-client process --remote=https://localhost:7701/api --tokenFile=token.txt --uuid=q78u-1z-0h5p --name=demo --start --application="My WAMAS Settings Server" --keepalive
COMMAND                                                                     PID   CPU[s]           START  CUR/ DES
q78u-1z-0h5p                                                                  0        0                  RUN/   ?
  master                                                                      0        0                  RUN/   ?
    My WAMAS Message Server                                                      0        0                 STOP/STOP
    My WAMAS Settings Server                                                 29575        0      2:01:09 PM  RUN/R(K)
    My WAMAS Worker Process                                                      0        0                 STOP/STOP
----

Make sure to replace the UUID with yours, and make sure that the application name matches your `template.json`. You can query all application status manually using `--status` like this:

----
$ minion-client process --remote=https://localhost:7701/api --tokenFile=token.txt --uuid=q78u-1z-0h5p --name=demo --status
COMMAND                                                                     PID   CPU[s]           START  CUR/ DES
q78u-1z-0h5p                                                                  0        0                  RUN/   ?
  master                                                                      0        0                  RUN/   ?
    My WAMAS Message Server                                                      0        0                 STOP/STOP
    My WAMAS Settings Server                                                 29575       13      2:01:09 PM  RUN/R(K)
    My WAMAS Worker Process                                                      0        0                 STOP/STOP
----

TIP: To stop a single application use `--stop` instead of `--start`.

If you want to stop all processes at once, use `--stop` without `--application`:

----
$ minion-client process --remote=https://localhost:7701/api --tokenFile=token.txt --uuid=q78u-1z-0h5p --name=demo --stop
COMMAND                                                                     PID   CPU[s]           START  CUR/ DES
q78u-1z-0h5p                                                                  0        0                  RUN/   ?
  master                                                                      0        0                  RUN/   ?
    My WAMAS Message Server                                                      0        0                 STOP/STOP
    My WAMAS Settings Server                                                 29575       14      2:01:09 PM  RUN/STOP
    My WAMAS Worker Process                                                    615        5      2:04:08 PM  RUN/STOP
----

NOTE: The processes are now in desired start `STOP`, and will be stopped by the PCU. Use `--status` again to see what is happening.

=== Inspect Deployment Directory

Take a look around in `/path/to/root/deploy` on the server. You will find a directory named like the instance UUID, and within it a `deploy` and a `data` directory. The `data` directory will hold persistent data like logs or persistent message queues - which should not be lost when updating the software.

----
$ ll root/deploy/q78u-1z-0h5p/
total 16
drwxr-xr-x 4 mduft salomon 4096 Jan  8 14:01 .
drwxr-xr-x 3 mduft salomon 4096 Jan  8 13:58 ..
drwxr-xr-x 3 mduft salomon 4096 Jan  8 14:01 data
drwxr-xr-x 3 mduft salomon 4096 Jan  8 13:58 deploy
----

IMPORTANT: Most data in the `deploy` directory is volatile and *not* re-used between deployed versions, so everything in there should not be edited manually (including configuration files!). The proper way is to edit configuration on the source (configuration UI) server, and push/deploy an updated version.

=== Undeploy/remove

You can undeploy/remove a deployed version using this command:

----
$ minion-client deployment --remote=https://localhost:7701/api --tokenFile=token.txt --name=demo --remove --manifest=q78u-1z-0h5p/root:1
----

This will remove the deployed directories from all minions and the deployment will no longer be listed. However the actual data is still in the hive, so re-deploying the applications is a cheap operation.

TODO: removing of instance manifests and instance fragment manifests from all slaves, etc. is not yet implemented.