= BDeploy Documentation

BDeploy is a speed and disc-usage optimized deployment solution for (tiny to large scale) applications.

== Deployment Systems on the Market

Existing systems either:

* Deploy a single (possibly large) application, don't update often (e.g. Oracle).
** Mostly a single "entry point" (service, manual started application, ...).
** Updates happen only from time to time, so they are "allowed" to be slow and manual.
* Deploy many (but small) applications, update frequently
** Using a hosting system like e.g. Kubernetes.

There is no solution which allows to install (really) large applications which have a dynamic (configurable) composition of service processes AND are updated frequently with small-ish deltas (potentially only configuration changes).

Additionally, most deployment solutions deploy either server or client applications, but not both together, also sharing configuration.

Unfortunately this is what "some software" needs: it's huge, it should be updated frequently during comissioning with tiny deltas (or configuration changes), processes are composable "freely" (from deployment perspective) and desktop clients need to be configured with values that match the server configuration.


== BDeploy is different

BDeploy aims at solving some (if not all) of these issues.

* Provides file-hash based delta updates through the BHive technology (Git-like hash-tree based file content management).
** Basically every update (application, configuration, etc.) is a "delta" update. The initial installation just has a relatively huge delta.
* Provides flexible configuration of process compositions (both server and client).
* Provides multi-target-node setup possibilities even for classic on premise deployments (i.e. without support of cluster software).
* Provides rich configuration possibilities for applications deployed. Each application can define it's own set of parameters known to it.
* Provides mechanisms to synchronize configuration between connected processes (e.g. server and client configuration).
* Provides a distribution mechanism which extends delta updating down to the client using a dedicated launcher.

All of this make BDeploy suitable for deploying highly dynamic products with extreme performance and flexibility demands.

=== A thought on the cloud

The cloud (and clusters) is unquestionably a thing that is not going to go away any time soon. Yet not all applications are read to be deployed in cloud environments. Also, even with current tooling, not every setup (especially in restricted environments) is feasible:

Even today, most tools related to "cloud" and "clusters" (e.g. "kubectl", "helm", etc.) are thinking about the cloud as a single thing. Some restricted environments would require to have a "cluster per installation" (e.g. per customer's restricted network).

In such environments, orchestration and management of the plethora of clusters is giving devops teams headaches. Also preparing and writing configuration for applications which then can be targeted at different cluster setups is everything but easy/simple.

BDeploy is built in a way that it can act as bridge to such systems (e.g. Kubernetes) in the future (support pending). It understands most of the concepts behind such cluster solutions and can be used to manage "clusters" instead of physical machines. This not only creates a tooling to manage clusters, but also allows to create hybrid solutions where a single setup is composed of a single configuration spanning physical, virtual, clustered and client nodes.

== Component documentation

* <<bhive.adoc#,BHive>>
* <<pcu.adoc#,PCU>>
* <<dcu.adoc#,DCU>>
* <<common.adoc#,Common>>
* <<minion.adoc#,Minion (Server)>>
* <<interfaces.adoc#,Common interfaces, descriptors, DTOs>>
* <<ui.adoc#,UI Front- and Backend>>

There is also a getting started for the command line applications:

* <<getting-started-cli.adoc#,Getting Started (CLI)>>
