=== How can I deploy a new product version?

Upgrading the *Product Version* that is used in an *Instance* requires two distinct steps:

. Uploading the new *Product Version*
. Upgrading the *Instance*

==== Upload Product Version

Uploading a new *Product Version* is done in the *Products* page of the *Instance Group*:

 . Click on the desired *Instance Group*
 . Click on btn:[Products] button in the main menu.
 . Click on the btn:[Upload Product] button in the toolbar.
 . Select the ZIP archive containing the new *Product Version*. This archive is typically created by your *Build* tool.
 . The product is uploaded, processed and will appear in the list of available products once successfully imported.

The *Product Version* is now available and can be used in all *Instances* of this *Instance Group*.

==== Upgrade Instance

Changing the *Product Version* of an *Instance* is done in the *Instance Configuration* dialog:

 . Navigate back to the *Instance Overview* dialog by clicking the btn:[Instances] button in the main menu.
 . Open the desired *Instance* by clicking it.
 . Each node displays the currently used product version. In case an update is available, a hint is shown in form of a small icon.
 . Clicking on this hint opens the *Instance Configuration* page along with the *Update Product* panel.
 .. You can also navigate to the *Instance Configuration* page by clicking the btn:[Instance Configuration] button in the main menu. This page shows a more prominent hint about the new *Product Version*.
 . Click on the btn:[Update] button of the desired product version
 . The update to the new *Product Version* is performed and validated on the server. It is - however - not saved, so you can undo/redo, perform changes - just like with any other configuration change.
 . Update _hints_ may be shown in a separate section which can be dismissed. Those are purely informative things which point to actions performed during the update which may or may not have an impact on the software.
 . _Validation Issues_ may be shown in a separate section if they occur due to the update. This can be a wide variety of things - all of them require manual intervention before you are able to save the *Instance Configuration*.
 . Adopt the configuration of the *Processes* as required
 . Click on *Save* in the top right corner to save this version

The *Instance* is now based on the new *Product Version*. Remember that the new *Instance Version* must be *Installed* and *Activated* so that the changes have an impact - clicking *Save* will bring you to the *Instance Dashboard* from where this can be performed directly.. Please read the <<_how_can_i_change_a_process_configuration,Process Configuration>> tutorial about more details how to do that.

