=== How can i change a process configuration?

Changing the configuration of a *Process* is done in the *Process Configuration Dialog*:

 . Click on the desired *Instance Group*
 . Click in the desired *Instance*
 . Ensure that the latest version is selected in the *Instance Version* sidebar.
 . Open the menu of the desired *Process* by clicking the three dots in the top right corner of the *Process Card*
 . Click on *Configure*. If *View* is shown then you are not on the latest *Instance Version*
 . Modify the *Process* as desired: Rename, Change Parameters, Add / Remove Parameters
 . Click on *Apply* in the top right corner if you are finished with this *Process*
 . A new _Locally Modified_ *Instance Version* has been created.
 . Repeat the steps 4-7 with every *Process* that should be adopted.
 . Click on *Save* in the top right corner.
 
The changes are now saved but they are not yet active. The new version must now be *Deployed* and all *Processes* must be restarted so that the changes have an effect.

 . Open the menu of the desired *Instance Version* by clicking the three dots on the *Instance Version Card*
 . Click on *Install* and wait for the operation to complete.
 . Click on *Activate*
 . A hint (Out-Of-Sync) will be displayed if a *Process* is running in an older version.
 . Stop the process by clicking on the *Process Card*. Click on the btn:[Stop] button.
 . Start the processes by click on the btn:[Start] button.
 . Repeat the steps 5-6 with each process that should be running
 . The hint (Out-Of-Sync) disappears once all processes are running in the active version.

The configuration changes are now live and all *Processes* are running again. The <<_process_settings,Process Settings>> and the <<_process_control,Process Control>> chapters provide more details about the step outlined in this tutorial.
 