/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.bdeploy.plugins.starter;

import java.util.Collection;
import java.util.Collections;

import io.bdeploy.api.plugin.v1.CustomEditor;
import io.bdeploy.api.plugin.v1.Plugin;
import io.bdeploy.api.plugin.v1.PluginAssets;

public class StarterEntry extends Plugin {
	
	@Override
	public Collection<Class<?>> getComponentClasses() {
		// All component classes are registered here. Component classes are JAX-RS resource implementations which
		// will be hosted by BDeploy in a dedicated per-plugin namespace on the server. Any frontend module which
		// is part of the plugin will have access to the APIs registered here.
		return Collections.singleton(StarterResource.class);
	}
	
	@Override
	public Collection<PluginAssets> getAssets() {
		return Collections.singletonList(new PluginAssets("/js", "/js"));
	}
	
	@Override
	public Collection<CustomEditor> getCustomEditors() {
		return Collections.singletonList(new CustomEditor("/js/encoding-editor.js", "BASE64_EDITOR", false));
	}
	
}
