=== Master

==== Modes of Operation

*BDeploy* may be set up in different modes, makeing a few different overal usage scenarios possible:

* `STANDALONE` mode: A standalone *BDeploy* master which is responsible for itself, its slaves, and every application deployed theron.
* `MANAGED` mode: A *BDeploy* master which is controlled by a `CENTRAL` *BDeploy* master. The `MANAGED` master can still be used nearly the same as the `STANDALONE` master, with very few restrictions. A `MANAGED` master can *additionally* be controlled indirectly through the attached `CENTRAL` master
* `CENTRAL` mode: Allows a central *BDeploy* master to control/manage multiple `MANAGED` masters. The `CENTRAL` master itself has no local deployment capabilities, but _just_ the ability to control other masters. Other than that, from a users perspective, the server handles mostly like a `STANDALONE` or `MANAGED` master directly.
* `SLAVE` mode: A slave which can be attached to either a `STANDALONE` or `MANAGED` server as additional node to run applications on.

image::images/Scenario_Standalone.svg[STANDALONE Deployment Scenario,align=center,width=480,link="images/Scenario_Standalone.svg"]

Compared to the rather straight forward standalone scenario above, a `CENTRAL` and `MANAGED` server setup, allows for more flixibility, manageable through a single Web UI:

image::images/Scenario_Central_Managed.svg[CENTRAL/MANAGED Deployment Scenario,align=center,width=480,link="images/Scenario_Central_Managed.svg"]

[NOTE]
You can still manage every `MANAGED` server directly through its own Web UI. Creation of new *Instance Groups* is restricted to the `CENTRAL` Web UI though.

*BDeploy*'s `CENTRAL` mode is built in a way that attached `MANAGED` servers can have an alternate URL, allowing it to manage servers which are known under a different name in the local network (e.g. VPN/NAT, alternate DNS, etc.).

[NOTE]
See <<Central/Managed Specific Configuration>> for more details.

==== Initialization
To start using BDeploy you will at least need a single *master*. The *master* needs to be initialized before it can be started.

The *root directory* contains all the runtime data. Best to select an empty directory in the data area of your system 
(e.g. /var/bdeploy on Unix) that is intended exclusively for this purpose. Keep the root directory separate from the BDeploy
binary installation. Make sure that there is enough space available. 

 bdeploy init --root=/path/to/storage --hostname=<hostname> --mode=STANDALONE --tokenFile=token.txt --port=7701

The `init` command will print a token. The token is written to a file when providing the `--tokenFile=token.txt` parameter.
This token can be used to access this server remotely through the command line, so make sure to store it in a safe place.

The `--mode` parameter of the `init` command is used to determine the future purpose of the *BDeploy* root. The mode can be `STANDALONE`, `MANAGED`, `CENTRAL` or `SLAVE`.

[NOTE]
It is not recommended (<<Migrating between Modes,but possible>>) to change the mode of an initialized root later, so take care to use the correct mode for the intended use.

The result of the `init` command is a *root directory* which can be used by the *master* or *slave* commands.

==== Launch
After the initialization - which needs to be done only once - the *master* can be started with the following command:

 bdeploy master --root=/path/to/storage

This will start the *master* server which also hosts the web UI: https://localhost:7701

[NOTE]
The server is using a self-signed certificate by default. Thus you need to instruct your browser to accept it. See <<Custom Certificate>> for instructions on how to provide a better certificate.

==== User
Only authenticated users have access to the web UI. Thus a new user must be created in order to be able to use the web UI

 bdeploy user --root=/path/to/storage --add=admin --password=admin --admin

The created user will be a global administrator, meaning that the user has permission to fully control the server. Without the `--admin` flag, the user will have no permissions per default. You have to create at least one administrator user to be able to set up the server (e.g. to configure LDAP authentication) and grant rights to other users.

[WARNING]
Don't use the depicted user and password, these are just samples.