=== Master

==== Initialization
To start using BDeploy you will at least need a single master. The master needs to be initialized before it can be started.
The root directory contains all runtime data. Make sure there is some room available:

 bdeploy init --root=/path/to/storage --dist=bdeploy-x.x.x.zip --hostname=$(hostname) # --tokenFile=token.txt

The --dist argument receives the binaries .zip you used to unpack the binaries from. This argument can explicitly be
set using '--dist=ignore' if you don't have this zip file. The effect is that this bdeploy will receive a larger (full)
update package once it is updated to another version.

The init command will print a token (you can capture the token in a file by giving '--tokenFile=token.txt' instead).
You need to copy this token - you will need this to be able to access this master from a remote server, e.g. a central
remote BDeploy master.

==== Launch
After the initialization - which needs to be done only once - the master can be started with the following command:

 bdeploy master --root=/path/to/storage

This will start the master server which also hosts the web UI: https://localhost:7701

[NOTE]
The server is using a self-signed certificate. Thus you need to instruct your browser to accept it.

==== User
Only authenticated users have access to the web UI. Thus a new user must be created in order to be able to use the web UI

 bdeploy user --root=/path/to/storage --add=admin --password=admin

All created users are administrators that have full access to the system. Permissions to restrict what a certain user can
do will be added in a future release.
