=== Master

==== Initialization
To start using BDeploy you will at least need a single *master*. The *master* needs to be initialized before it can be started.

The *root directory* contains all the runtime data. Best to select an empty directory in the data area of your system 
(e.g. /var/bdeploy on Unix) that is intended exclusively for this purpose. Keep the root directory separate from the BDeploy
binary installation. Make sure that there is enough space available. 

 bdeploy init --root=/path/to/storage --hostname=<hostname> # --tokenFile=token.txt

The `init` command will print a token (you can capture the token in a file by giving `--tokenFile=token.txt` instead).
You need to copy this token - you will need this to be able to access this master from a remote server, e.g. a central
remote *BDeploy master*.

The result of the `init` command is a *root directory* which can be used by the *master* or *slave* commands.

[NOTE]
Before *BDeploy 1.2.0* it was necessary to specify a `--dist` argument. This is no longer required, but still supported. Also,
the *BDeploy Launcher* used to be a separate binary distribution. It is now included in the main *BDeploy* distribution, and
will be set up for you by the `init` command

==== Launch
After the initialization - which needs to be done only once - the *master* can be started with the following command:

 bdeploy master --root=/path/to/storage

This will start the *master* server which also hosts the web UI: https://localhost:7701

[NOTE]
The server is using a self-signed certificate by default. Thus you need to instruct your browser to accept it.

==== User
Only authenticated users have access to the web UI. Thus a new user must be created in order to be able to use the web UI

 bdeploy user --root=/path/to/storage --add=admin --password=admin

All created users are administrators that have full access to the system. Permissions to restrict what a certain user can
do will be added in a future release.
