=== Slave

Slaves are optional an only required in case that the application that you want to deploy should run on different servers. 

==== Initializing
Slaves must be initialized on the according machines (or on the same machine using non-default ports; the default port is 7701). 
The command is the same as the one used to initialize the master. Pass (for example) '--port=7702' to change the
default port to some other value to avoid conflicts. Running multiple bdeploy minions on the same machine is
supported for testing, but not recommended for productive setups (as the master can be deployed to directly).

 bdeploy init --root=/path/to/slave/storage --hostname=<hostname> # --tokenFile=token.txt # --port=7702

Again, the init command will output the root access token for this slave. You need it to register the slave with the
master, so keep it around or use '--tokenFile=slave.txt' to store the token into a file.

==== Launch
After the initialization - which needs to be done only once - the slave can be started with the following command:

 bdeploy slave --root=/path/to/storage

==== Registration
To register a slave with the master use this command on the master's root:

 bdeploy slave --add=slave-name --root=/path/to/master/storage --remote=https://slave-host:7702/api
    --tokenFile=slave.txt # or --token=<PASTED-TOKEN>

NOTE: Both the 'https' (beware the 's') and the '/api' suffix are important!

The slave is now registered as 'slave-name'. This is the name which is reported when querying nodes from the master.
This is also the name displayed when configuring applications to run on certain nodes later on.

