name: Linux (x64)
on: [push]

jobs:
  build:
    name: Build and test on Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout from GIT
      uses: actions/checkout@v5
        
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version-file: .java-version

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build and Test
      id: build
      run: ./gradlew --stacktrace --scan clean build

    - name: Upload dist zip
      uses: actions/upload-artifact@v4
      with:
        name: snapshot-dist-zip
        path: minion/build/distributions

    - name: Upload playwright results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-results
        path: ui/webapp/playwright/results

